import 'package:hive_flutter/hive_flutter.dart';

import '../models/quest.dart';

/// On-device store for the dual-track tracker output.
///
/// One [TrackingDb] instance services many events sequentially (R0.1 only
/// allows one active quest at a time per locked decision #9, but a hot-
/// restart can leave a previous event's box around for backfill). Each
/// active event opens three Hive boxes:
///
///   - `tracking_[eventId]_locus`  — `Box<LocusEvent>` keyed by event id
///   - `tracking_[eventId]_pings`  — `Box<GeolocatorPing>` keyed by id
///   - `tracking_[eventId]_meta`   — generic box with two keys:
///       `synced_locus` → `List<String>` of synced LocusEvent ids
///       `synced_pings` → `List<String>` of synced GeolocatorPing ids
///
/// `LocusEvent.id` and `GeolocatorPing.id` are expected to be UUIDs
/// (generated by the trackers in Session 3) — globally unique across all
/// events. `markSynced` therefore doesn't need an `eventId` argument; the
/// scan visits every currently-open event and marks ids that match.
class TrackingDb {
  static const String _kSyncedLocus = 'synced_locus';
  static const String _kSyncedPings = 'synced_pings';

  final Map<String, _EventBoxes> _open = {};

  Future<void> open(String eventId) async {
    if (_open.containsKey(eventId)) return;
    final locus = await Hive.openBox<LocusEvent>('tracking_${eventId}_locus');
    final pings = await Hive.openBox<GeolocatorPing>('tracking_${eventId}_pings');
    final meta = await Hive.openBox('tracking_${eventId}_meta');
    _open[eventId] = _EventBoxes(locus: locus, pings: pings, meta: meta);
  }

  Future<void> close(String eventId) async {
    final boxes = _open.remove(eventId);
    if (boxes == null) return;
    await boxes.locus.close();
    await boxes.pings.close();
    await boxes.meta.close();
  }

  /// Closes every event currently open. Useful in tests.
  Future<void> closeAll() async {
    final ids = _open.keys.toList(growable: false);
    for (final id in ids) {
      await close(id);
    }
  }

  Future<void> appendLocusEvent(String eventId, LocusEvent e) async {
    await _require(eventId).locus.put(e.id, e);
  }

  Future<void> appendGeolocatorPing(String eventId, GeolocatorPing p) async {
    await _require(eventId).pings.put(p.id, p);
  }

  Future<List<LocusEvent>> unsyncedLocusEvents(String eventId) async {
    final boxes = _require(eventId);
    final synced = _readSyncedSet(boxes.meta, _kSyncedLocus);
    return boxes.locus.values
        .where((e) => !synced.contains(e.id))
        .toList(growable: false);
  }

  Future<List<GeolocatorPing>> unsyncedGeolocatorPings(String eventId) async {
    final boxes = _require(eventId);
    final synced = _readSyncedSet(boxes.meta, _kSyncedPings);
    return boxes.pings.values
        .where((p) => !synced.contains(p.id))
        .toList(growable: false);
  }

  /// Marks the given ids as synced across every currently-open event.
  /// Ids are globally unique UUIDs, so a scan is safe and cheap.
  Future<void> markSynced({
    required List<String> locusIds,
    required List<String> pingIds,
  }) async {
    if (locusIds.isEmpty && pingIds.isEmpty) return;
    for (final boxes in _open.values) {
      if (locusIds.isNotEmpty) {
        final next = _readSyncedSet(boxes.meta, _kSyncedLocus)..addAll(locusIds);
        await boxes.meta.put(_kSyncedLocus, next.toList());
      }
      if (pingIds.isNotEmpty) {
        final next = _readSyncedSet(boxes.meta, _kSyncedPings)..addAll(pingIds);
        await boxes.meta.put(_kSyncedPings, next.toList());
      }
    }
  }

  /// Total rows persisted for [eventId] (synced + unsynced, locus + pings).
  /// Diagnostics only — used by the active-quest screen for "X points
  /// collected" if we want to surface raw counts.
  Future<int> totalCount(String eventId) async {
    final boxes = _require(eventId);
    return boxes.locus.length + boxes.pings.length;
  }

  _EventBoxes _require(String eventId) {
    final boxes = _open[eventId];
    if (boxes == null) {
      throw StateError('TrackingDb not open for $eventId. Call open() first.');
    }
    return boxes;
  }

  Set<String> _readSyncedSet(Box<dynamic> meta, String key) {
    final raw = meta.get(key);
    if (raw is List) return raw.cast<String>().toSet();
    return <String>{};
  }
}

class _EventBoxes {
  final Box<LocusEvent> locus;
  final Box<GeolocatorPing> pings;
  final Box<dynamic> meta;

  _EventBoxes({
    required this.locus,
    required this.pings,
    required this.meta,
  });
}
